# +-------------------------------------+
# |config.yaml                          |
# |Every setting here is case sensitive!|
# +-------------------------------------+

#Default directory is 'C:/Program Files (x86)/Steam/steamapps/common/FPSAimTrainer/FPSAimTrainer/stats'
#Make sure that you use '/', not '\'.
directory: ''
sheet_name: ''
worksheet_name: ''

#Currently only 'voltaic' and 'aimerz' are supported!
benchmarks: ''
